# Generated by Django 3.1 on 2020-10-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTrucks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_location', models.CharField(max_length=200)),
                ('food_type', models.CharField(max_length=200)),
                ('open_time', models.CharField(max_length=200)),
                ('closing_time', models.CharField(max_length=200)),
            ],
        ),
    ]
